[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "dist"

# [[headers]]
  # Define which paths this specific [[headers]] block will cover.
  # for = "/sitemap.xml"
  # status = 200
  # content-type = "application/xml"

[[hea# ders]]
  # Define which paths this specific [[headers]] block will cover.
  # for = "/*.css"

  # [headers.values]
    # X-Frame-Options = "DENY"
    # X-XSS-Protection = "1; mode=block"
    # Content-Security-Policy = "frame-ancestors https://www.facebook.com"

    # Multi-value headers are expressed with multi-line strings.
	  # cache-control = '''
	  # max-age=0,
	  # no-cache,
	  # no-store,
	  # must-revalidate'''

    # Basic-Auth allows you to password protect your whole site.
    # This feature may not be available on all plans.
    # Basic-Auth = "someuser:somepassword anotheruser:anotherpassword"