[[redirects]]
  from = "/sitemap"
  to = "/sitemap.xml"
  status = 200
  [redirects.headers]
    # X-From = "Netlify"
    # X-Api-Key = "some-api-key-string"
    access-control-allow-origin = *
    content-type = application/xml

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*.css"

  [headers.values]
    # X-Frame-Options = "DENY"
    # X-XSS-Protection = "1; mode=block"
    # Content-Security-Policy = "frame-ancestors https://www.facebook.com"

    # Multi-value headers are expressed with multi-line strings.
	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''

    # Basic-Auth allows you to password protect your whole site.
    # This feature may not be available on all plans.
    # Basic-Auth = "someuser:somepassword anotheruser:anotherpassword"